export default {
  GET_USER_LEAGUES: "GET_USER_LEAGUES",
  GET_USER_LEAGUES_SUCCESS: "GET_USER_LEAGUES_SUCCESS",
  GET_USER_LEAGUES_FAILURE: "GET_USER_LEAGUES_FAILURE",
  NEW_LEAGUE: "NEW_LEAGUE",
  NEW_LEAGUE_SUCCESS: "NEW_LEAGUE_SUCCESS",
  NEW_LEAGUE_FAILURE: "NEW_LEAGUE_FAILURE",
  GET_LEAGUE: "GET_LEAGUE",
  GET_LEAGUE_SUCCESS: "GET_LEAGUE_SUCCESS",
  GET_LEAGUE_FAILURE: "GET_LEAGUE_FAILURE",
  GET_LEAGUE_USERS: "GET_LEAGUE_USERS",
  GET_LEAGUE_USERS_SUCCESS: "GET_LEAGUE_USERS_SUCCESS",
  GET_LEAGUE_USERS_FAILURE: "GET_LEAGUE_USERS_FAILURE",
}